EventReservation.PL/Controllers/EventsController.cs
using AutoMapper;
using EventReservation.BLL.InterFaces;
using EventReservation.BLL.Repositories;
using EventReservation.DAL.Models;
using EventReservation.PL.Helper;
using EventReservation.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EventReservation.PL.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private IEventRepository _eventRepository;
        private readonly IMapper _mapper;

        public EventsController(IEventRepository eventRepository,  IMapper mapper )
        {
            _eventRepository = eventRepository;
            _mapper = mapper;
          
        }
        // GET: HomeController1
        public async Task<IActionResult> Index(string searchInput)
        {
            var events = Enumerable.Empty<Events>();
            if (string.IsNullOrEmpty(searchInput))
            {
                events = await  _eventRepository.GetAll();
            }
            else
            {
                events = await _eventRepository.GetByName(searchInput);
            }

            var result = _mapper.Map<IEnumerable<EventsViewModel>>(events);

            return View(result);
        }



        // GET: HomeController1/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EventsViewModel model)
        {

            model.ImageName = DocumentSettings.UploadFile(model.Image, "images");
            var _event = _mapper.Map<Events>(model);
            var count = _eventRepository.Add(_event);
             if(count > 0 )
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
                
        
        }
        
        public async Task<IActionResult> Details(int? Id, string ViewName = "Details")
        {
            if (Id is null)
            {
                return BadRequest();//400
            }
            var events = await _eventRepository.Get(Id.Value);

            var eventViewModel = _mapper.Map<EventsViewModel>(events);

            if (events is null)
            {
                return NotFound();//404
            }


            return View(ViewName, eventViewModel);
        }
        [HttpGet]
        public Task<IActionResult> Edit(int? Id)
        {
            return Details(Id, "Edit");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult  Edit([FromRoute] int? id, EventsViewModel model)
        {
            if (id != model.ID)
            {
                return BadRequest();
            }
            if (model.ImageName is not null)
            {
                DocumentSettings.DeleteFile(model.ImageName, "images");
                model.ImageName = DocumentSettings.UploadFile(model.Image, "images");

            }
            else
            {
                model.ImageName = DocumentSettings.UploadFile(model.Image, "images");
            }

                var _event = _mapper.Map<Events>(model);
                var count = _eventRepository.Update(_event);
                if (count > 0) { return RedirectToAction(nameof(Index)); }
                else { return View(model); }
            
            
        }
        [HttpGet]
        public Task<IActionResult> Delete(int? Id)
        {
            return Details(Id, "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Delete([FromRoute] int? id, EventsViewModel model)
        {
            if (id != model.ID)
            {
                return BadRequest();
            }
            var events = _mapper.Map<Events>(model);
            if (ModelState.IsValid)//server side validation
            {
                int count =  _eventRepository.Delete(events);
            if(count > 0)
                {
                    DocumentSettings.DeleteFile(model.ImageName, "images");
                    return RedirectToAction(nameof(Index));
                }
                
                
            }

            return View(model);
        }

       
    }
}

EventReservation.PL/Controllers/UserController.cs
using EventReservation.DAL.Models;
using EventReservation.PL.Models;
using EventReservation.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoPL.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }


        public async Task<IActionResult> Index(string searchinput)
        {
            var users = Enumerable.Empty<UserViewModel>();

            //  _unitOfWork.Complete();  

            if (string.IsNullOrEmpty(searchinput))
            {
                users = await _userManager.Users.Select(U => new UserViewModel()
                {
                    Id = U.Id,
                    FirstName = U.FirstName,
                    LastName = U.LastName,
                    Email = U.Email,
                    UserSSN = U.UserSSN,
                    Roles = _userManager.GetRolesAsync(U).Result
                }).ToListAsync() ;

            }
            else
            {
                users = await _userManager.Users.Where(U => U.Email
                                                            .ToLower()
                                                            .Contains(searchinput.ToLower()))
                                                            .Select(U => new UserViewModel()
                                                            {
                                                                Id = U.Id,
                                                                FirstName = U.FirstName,
                                                                LastName = U.LastName,
                                                                Email = U.Email,
                                                                UserSSN = U.UserSSN,
                                                                Roles = _userManager.GetRolesAsync(U).Result
                                                            }).ToListAsync();
            }

   

            return View(users);
        }

        public async Task<IActionResult> Details(string? Id, string ViewName = "Details")
        {
            if (Id is null)
            {
                return BadRequest();//400
            }
            var userFromDb = await _userManager.FindByIdAsync(Id);

           

            if (userFromDb is null)
            {
                return NotFound();//404
            }

            var user = new UserViewModel()
            {
                Id = userFromDb.Id,
                FirstName = userFromDb.FirstName,
                LastName = userFromDb.LastName,
                Email = userFromDb.Email,
                UserSSN= userFromDb.UserSSN,
                Roles = _userManager.GetRolesAsync(userFromDb).Result
            };

            return View(ViewName, user);
        }
        [HttpGet]
        public Task<IActionResult> Edit(string? Id)
        {
            //ViewData["Departments"] = _departmentRepository.GetAll();
            return Details(Id, "Edit");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string? id, UserViewModel model)
        {
            if (id != model.Id)
            {
                return BadRequest();
            }
          
            
            if (ModelState.IsValid)//server side validation
            {
                var userFromDb = await _userManager.FindByIdAsync(id);


                if (userFromDb is null)
                {
                    return NotFound();//404
                }

                userFromDb.FirstName = model.FirstName;
                userFromDb.LastName = model.LastName;
                userFromDb.Email = model.Email;
                userFromDb.UserSSN = model.UserSSN;
                userFromDb.Id = model.Id;
                
                var result = await  _userManager.UpdateAsync(userFromDb);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(model);
        }
        [HttpGet]
        public Task<IActionResult> Delete(string? Id)
        {
            return Details(Id, "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string? id, UserViewModel model)
        {
            if (id != model.Id)
            {
                return BadRequest();
            }


            if (ModelState.IsValid)//server side validation
            {
                var userFromDb = await _userManager.FindByIdAsync(id);


                if (userFromDb is null)
                {
                    return NotFound();//404
                }

             
                var result = await _userManager.DeleteAsync(userFromDb);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(model);
        }
    }
}

EventReservation.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib @ViewData["Title"]  Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
    
  
    
    <link href="~/css/authstyle.css" rel="stylesheet" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("ValidationSection",required:false);
</body>
</html>

EventReservation.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string 
<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i>Details
    </a>
</td>
<td>
    <a  asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i>Update
    </a>
</td>
<td>
    <a  asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i>Delete
    </a>
</td>

EventReservation.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eventaty</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventReservation.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eventaty</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                     @*    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li> *@

                        <li class="nav-item">
                            <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EventReservation.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationSection", required: false)
</body>
</html>