EventReservation.PL/ViewModels/EventsViewModel.cs
using EventReservation.DAL.Models;
using System.ComponentModel.DataAnnotations;

namespace EventReservation.PL.ViewModels
{
    public class EventsViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Event Code IS Required !!")]
        public string EventCode { get; set; }

        [Required(ErrorMessage = "Event Name IS Required !!")]
        public string EventName { get; set; }

        [Required(ErrorMessage = "Event Organizer IS Required !!")]
        public string EventOrganizer { get; set; }

        [Required(ErrorMessage = "Event Date IS Required !!")]
        public DateTime DateTime { get; set; }

        [Required(ErrorMessage = "Event Location IS Required !!")]
        public string EventLocation { get; set; }

        public string? ImageName { get; set; }

        public IFormFile? Image { get; set; }

        public string? EventDuration { get; set; }

        [Required(ErrorMessage = "Event Description IS Required !!")]

        public string EventDescription { get; set; }

        public ICollection<Voucher>? Vouchers { get; set; }
    }
}

EventReservation.PL/Controllers/EventsController.cs
using AutoMapper;
using EventReservation.BLL.InterFaces;
using EventReservation.BLL.Repositories;
using EventReservation.DAL.Models;
using EventReservation.PL.Helper;
using EventReservation.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EventReservation.PL.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private IEventRepository _eventRepository;
        private readonly IMapper _mapper;

        public EventsController(IEventRepository eventRepository,  IMapper mapper )
        {
            _eventRepository = eventRepository;
            _mapper = mapper;
          
        }
        // GET: HomeController1
        public async Task<IActionResult> Index(string searchInput)
        {
            var events = Enumerable.Empty<Events>();
            if (string.IsNullOrEmpty(searchInput))
            {
                events = await  _eventRepository.GetAll();
            }
            else
            {
                events = await _eventRepository.GetByName(searchInput);
            }

            var result = _mapper.Map<IEnumerable<EventsViewModel>>(events);

            return View(result);
        }



        // GET: HomeController1/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EventsViewModel model)
        {

            model.ImageName = DocumentSettings.UploadFile(model.Image, "images");
            var _event = _mapper.Map<Events>(model);
            var count = _eventRepository.Add(_event);
             if(count > 0 )
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
                
        
        }
        
        public async Task<IActionResult> Details(int? Id, string ViewName = "Details")
        {
            if (Id is null)
            {
                return BadRequest();//400
            }
            var events = await _eventRepository.Get(Id.Value);

            var eventViewModel = _mapper.Map<EventsViewModel>(events);

            if (events is null)
            {
                return NotFound();//404
            }


            return View(ViewName, eventViewModel);
        }
        [HttpGet]
        public Task<IActionResult> Edit(int? Id)
        {
            return Details(Id, "Edit");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult  Edit([FromRoute] int? id, EventsViewModel model)
        {
            if (id != model.ID)
            {
                return BadRequest();
            }
            if (model.ImageName is not null)
            {
                DocumentSettings.DeleteFile(model.ImageName, "images");
                model.ImageName = DocumentSettings.UploadFile(model.Image, "images");

            }
            else
            {
                model.ImageName = DocumentSettings.UploadFile(model.Image, "images");
            }

                var _event = _mapper.Map<Events>(model);
                var count = _eventRepository.Update(_event);
                if (count > 0) { return RedirectToAction(nameof(Index)); }
                else { return View(model); }
            
            
        }
        [HttpGet]
        public Task<IActionResult> Delete(int? Id)
        {
            return Details(Id, "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Delete([FromRoute] int? id, EventsViewModel model)
        {
            if (id != model.ID)
            {
                return BadRequest();
            }
            var events = _mapper.Map<Events>(model);
            if (ModelState.IsValid)//server side validation
            {
                int count =  _eventRepository.Delete(events);
            if(count > 0)
                {
                    DocumentSettings.DeleteFile(model.ImageName, "images");
                    return RedirectToAction(nameof(Index));
                }
                
                
            }

            return View(model);
        }

       
    }
}

EventReservation.PL/Controllers/TicketController.cs
using EventReservation.BLL.InterFaces;
using EventReservation.DAL.Models;
using EventReservation.PL.Helper;
using EventReservation.PL.Helper.QrCodeHelper;
using EventReservation.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;
using Microsoft.Extensions.Logging;
using QRCoder;
using System.Collections.Generic;
using System.Security.Claims;

namespace EventReservation.PL.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        private ITicketRepository _ticketRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMailSettings _mailSettings;
        private readonly IQrCodeGeneratorHelper _qrCodeGenerator;

        public TicketController(
            ITicketRepository ticketRepository ,
            UserManager<ApplicationUser> userManager,
            IMailSettings mailSettings,
            IQrCodeGeneratorHelper qrCodeGenerator)
        {
            _ticketRepository = ticketRepository;
            _userManager = userManager;
            _mailSettings = mailSettings;
            _qrCodeGenerator = qrCodeGenerator;
        }
        // GET: HomeController1
        public async Task<IActionResult> Index([FromRoute] int id)
        {
            ViewData["CurrentEventID"] = id;
            var tickets = await _ticketRepository.GetEventTicket(id);
            if (tickets is null)
            {
                return BadRequest();
            }
            else
            {
                return View(tickets);
            }

        }
        [HttpGet]
        public IActionResult CreateTickets()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateTickets([FromRoute] int id, TicketViewModel model)
        {
           
            int number = model.TicketsNumber;
            int count = 0;
            for (int i = 0; i < number; i++)
            {
                var newTicket = new Ticket()
                {
                    EventID = id,
                    TicketCode = Guid.NewGuid().ToString(),
                    TicketPrice = model.TicketPrice,
                    TicketCategory = model.TicketCategory,

                };

                count = _ticketRepository.Add(newTicket);
            }
            if (count > 0) { return RedirectToAction(nameof(Index), new {id = id}); }
            else { return View(model); }

        }
        [HttpGet]
        public async Task<IActionResult> DeleteEventTicket([FromRoute] int id)
        {
            ViewData["CurrentEventID"] = id;
            var tickets = await _ticketRepository.GetEventTicket(id);
            if (tickets is null)
            {
                return BadRequest();
            }
            else
            {
                return View(tickets);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteEventTicket([FromRoute] int id , IEnumerable<Ticket> tickets)
        {
             await  _ticketRepository.DeleteEventTicketAsync(id);
            return RedirectToAction(nameof(Index), new { eventId = id }); // Redirect back to ManageTickets view
        }


        [HttpGet]
        public IActionResult BuyTicket([FromRoute] int id)
        {
            var categories = _ticketRepository.CategoriesToBeBought(id);
            ViewData["CurrentEventID"] = id;

            return View(categories);
           
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<IActionResult> BuyTicket([FromRoute]int id ,  string customData)
        {
            
            var ticket =   _ticketRepository.BuyTicket(id, customData);

            var userEmail = User.FindFirstValue(ClaimTypes.Email);

            var user = await _userManager.FindByEmailAsync(userEmail);

            //var qrCode = _qrCodeGenerator.GenerateQrCode(ticket.TicketCode);

         

           

            var emailToSend = new Email()
            {
                Subject = "Your Ticket",
                Recipients = userEmail,
                Body = ticket.TicketCode
            };

            if (ticket is not null)
            {
                ticket.TicketState = true;
                ticket.OwnerID = user.Id;

                //string QRCodeAsImageBase64 = $"data:image/png;base64,{Convert.ToBase64String(qrCode)}";


                //await _mailSettings.SendEmailWithQRCodeAsync(emailToSend, QRCodeAsImageBase64);
                await _mailSettings.SendEmailAsync(emailToSend);
                //ViewData["QrCodeImage"] = QRCodeAsImageBase64;
                var categories = _ticketRepository.CategoriesToBeBought(id);
                ViewData["CurrentEventID"] = id;

                return RedirectToAction(nameof(ViewTicket), new { ticketId = id });

            }
            else
            {
                return BadRequest();
            }
        }



        [HttpGet]
        public async Task<IActionResult> ViewTicket( int ticketID)
        {
            var ticket =  await _ticketRepository.Get(ticketID);
            if (ticket is not null)
            {
                var ticketCode = ticket.TicketCode;
                var qrCode = _qrCodeGenerator.GenerateQrCode(ticketCode);
                string QRCodeAsImageBase64 = $"data:image/png;base64,{Convert.ToBase64String(qrCode)}";
                QrCodeViewModel qrCodeTestView = new QrCodeViewModel()
                {
                    QrCodeImageUrl = QRCodeAsImageBase64
                };

                return View(qrCodeTestView);
            }
            
            return View();

        }
       

    }
}

EventReservation.PL/Controllers/VoucherController.cs
using EventReservation.BLL.InterFaces;
using EventReservation.BLL.Repositories;
using EventReservation.DAL.Models;
using EventReservation.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EventReservation.PL.Controllers
{
    [Authorize]
    public class VoucherController : Controller
    {
        private readonly IVoucherRepository _voucherRepository;

        public VoucherController(IVoucherRepository voucherRepository)
        {
            _voucherRepository = voucherRepository;
        }
        // GET: HomeController1
        public async Task<IActionResult> Index([FromRoute] int id)
        {
            ViewData["CurrentEventID"] = id;
            var vouchers = await _voucherRepository.GetVoucher(id);
            if (vouchers is null)
            {
                return BadRequest();
            }
            else
            {
                return View(vouchers);
            }

        }
        [HttpGet]
        public IActionResult CreateVouchers()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateVouchers([FromRoute] int id, VoucherViewModel model)
        {
            ViewData["CurrentEventID"] = id;
            int number = model.VouchersNumber;
            int count = 0;
            for (int i = 0; i < number; i++)
            {
                var newVoucher = new Voucher()
                {
                    EventID = id,
                    VoucherCode = Guid.NewGuid().ToString(),
                    VoucherDiscount = model.VoucherDiscount,
                   

                };

                count = +_voucherRepository.Add(newVoucher);
            }
            if (count > 0) { return RedirectToAction(nameof(Index), new {id=id}); }
            else { return View(model); }

        }
        [HttpGet]
        public async Task<IActionResult> DeleteEventVoucher([FromRoute] int id)
        {
            ViewData["CurrentEventID"] = id;
            var vouchers = await _voucherRepository.GetVoucher(id);
            if (vouchers is null)
            {
                return BadRequest();
            }
            else
            {
                return View(vouchers);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteEventVoucher([FromRoute] int id, IEnumerable<Voucher> vouchers)
        {
            await _voucherRepository.DeleteEventVoucherAsync(id);
            return RedirectToAction(nameof(Index), new { eventId = id }); // Redirect back to Manage Vouchers view
        }
    }
}

EventReservation.PL/Views/Events/Create.cshtml
@model EventsViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Create Page </h4>
<br />
<br/> 

<form asp-controller="Events" asp-action="Create" enctype="multipart/form-data">
    <partial name="EventsParialViews/CreatEditPartialView" model="Model" />
    <input type ="submit" value="Create" class="btn btn-primary"/>
    <a asp-controller="Events" asp-action="Index" class="btn btn-light">Back to List</a>
</form> 

@section ValidationSection
 {
    <partial name="_ValidationScriptsPartial" />

}

EventReservation.PL/Views/Events/Delete.cshtml
@model EventsViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<br />
<br />

<form asp-controller="Events" asp-action="Delete">
    <partial name="EventsParialViews/DetailsDeletePartialView" model="Model" />
    <input type="submit" value="Delete" class="btn btn-danger"/a>
    <a asp-controller="Events" asp-action="Index" class="btn btn-light">Back to List</a>
</form>

EventReservation.PL/Views/Events/Details.cshtml
@model EventsViewModel

    @{
    ViewData["Title"] = "Details";
}
<h1>Details</h1>
<br />
<br />

<div asp-controller="Events" asp-action="Details">
    <partial name="EventsParialViews/DetailsDeletePartialView" model="Model" />
    <a asp-controller="Events" asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-warning">Edit</a>

    <td>
        <a asp-controller="Ticket" asp-action="BuyTicket" asp-route-id="@Model.ID" class="btn btn-info">
            <i class="fas fa-eye"></i>Buy Tickets
        </a>
    </td>

    <a asp-controller="Events" asp-action="Index" class="btn btn-light">Back to List</a>
</div> 

EventReservation.PL/Views/Events/Edit.cshtml
@model EventsViewModel

@{
    ViewData["Title"] = "Edit";
    
}

<h1>Edit</h1>

<h4>Create Page </h4>
<br />
<br />

<form asp-controller="Events" asp-action="Edit" enctype="multipart/form-data">
    <partial name="EventsParialViews/CreatEditPartialView" model="Model" />
    <input type="submit" value="Save" class="btn btn-primary" />
    <td>
        <a asp-controller="Ticket" asp-action="Index" asp-route-id="@Model.ID" class="btn btn-info">
            <i class="fas fa-eye"></i>Manage Tickets
        </a>
    </td>
    <td>
        <a asp-controller="Voucher" asp-action="Index" asp-route-id="@Model.ID" class="btn btn-success">
            <i class="fas fa-eye"></i>Manage Voucher
        </a>
    </td>
    <a asp-controller="Events" asp-action="Index" class="btn btn-light">Back to List</a>
</form>
@section ValidationSection
{
    <partial name="_ValidationScriptsPartial" />

}

EventReservation.PL/Views/Events/Index.cshtml
@model IEnumerable<EventsViewModel>

@{
    ViewData["Title"] = "All Events";
}

<h1>All Events</h1>
<br /> 

<br /> 


<form asp-action="index" class="m-5">
    <div class="row">
        <div class="col-8">
            <input type="text" name="SearchInput" id="SearchInput" class="form-control" placeholder="Search" />
        </div>
        <div class="col-4">
            <input type="submit" value="search" class="btn btn-success" />
        </div>
    </div>

</form>



<a asp-controller="Events" asp-action="Create" class=" btn btn-primary">Create Event</a>

<br/>
<br/> 
@if (Model.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(E=>E.Image)</th>
                <th>@Html.DisplayNameFor(E => E.EventName)</th>
                <th>@Html.DisplayNameFor(E => E.EventDescription)</th>
                <th>@Html.DisplayNameFor(E => E.EventLocation)</th>
                <th>@Html.DisplayNameFor(E => E.DateTime)</th>
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        <img src="~/files/images/@item.ImageName" width="75" class="img-fluid rounded-circle" />
                    </td>
                    <td>@item.EventName</td>
                    <td>@item.EventDescription</td>
                    <td>@item.EventLocation</td>
                    <td>@item.DateTime</td>
                    <partial name="_ButtonsPartialView" model="@item.ID.ToString()" />
                </tr> 
            }
        </tbody>
    </table>
}
else
{
    <div class="mt-4 alert alert-warning">
        <h4>there is no Events :(</h4>
    </div>
}